pipeline {
   agent any

    tools {
        go 'go1.18'
    }

    environment {
        GO114MODULE = 'on'
        CGO_ENABLED = 0
        GOPATH = "${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}"
    }

   stages {
      stage('pull code') {
         steps {
            echo 'pull code'
            git branch: 'main', credentialsId: 'heartleo-github-token', url: 'https://github.com/heartleo/cicd.git'
         }
      }
      stage('build code') {
         steps {
            echo 'build code'
            sh 'go version'
         }
      }
      stage('deploy project') {
         steps {
            echo 'deploy project'
         }
      }
   }
}
